wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.9.18
    cli_version: 0.16.2
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1705541907.42946
    t:
      1:
      - 55
      3:
      - 14
      - 23
      4: 3.9.18
      5: 0.16.2
      8:
      - 1
      - 5
      13: linux-x86_64
