wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.9.18
    cli_version: 0.16.2
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1705542128.033165
    t:
      1:
      - 55
      2:
      - 5
      - 53
      - 55
      3:
      - 2
      - 3
      - 5
      - 14
      - 23
      4: 3.9.18
      5: 0.16.2
      8:
      - 1
      - 5
      13: linux-x86_64
    framework: sklearn
    session_history: code/_session_history.ipynb
lr:
  desc: null
  value: 1.0e-05
seed:
  desc: null
  value: 1
gamma:
  desc: null
  value: 0.01
epochs:
  desc: null
  value: 50
no_cuda:
  desc: null
  value: false
use_glove:
  desc: null
  value: true
batch_size:
  desc: null
  value: 512
save_model:
  desc: null
  value: false
max_ques_len:
  desc: null
  value: 20
val_question:
  desc: null
  value: /home/ndhuynh/data/simpsonsvqa/v1_Question_Val_simpsons_vqa.json
question_path:
  desc: null
  value: /home/ndhuynh/data/simpsonsvqa/v1_Question_Train_simpsons_vqa.json
stat_ques_list:
  desc: null
  value:
  - /home/ndhuynh/data/simpsonsvqa/v1_Question_Train_simpsons_vqa.json
  - /home/ndhuynh/data/simpsonsvqa/v1_Question_Val_simpsons_vqa.json
train_question:
  desc: null
  value: /home/ndhuynh/data/simpsonsvqa/v1_Question_Train_simpsons_vqa.json
val_annotation:
  desc: null
  value: /home/ndhuynh/data/simpsonsvqa/v1_Annotation_Val_simpsons_vqa.json
test_batch_size:
  desc: null
  value: 1000
train_annotation:
  desc: null
  value: /home/ndhuynh/data/simpsonsvqa/v1_Annotation_Train_simpsons_vqa.json
